# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'GymVision' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # For AWSS3
  pod 'AWSCore'
  pod 'AWSS3'

  # Gif Display
  pod 'SwiftGifOrigin', '~> 1.7.0'

  # Pods for GymVision

  target 'GymVisionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GymVisionUITests' do
    # Pods for testing
  end

end
